//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur_has_Partie
    {
        public int id_joueur { get; set; }
        public int id_partie { get; set; }
        public Nullable<int> JhP_flag { get; set; }
        public Nullable<int> JhP_ordre_de_jeu { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Joueur Joueur1 { get; set; }
        public virtual Partie Partie { get; set; }
    }
}
