//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur_has_Partie
    {
        public int id_joueur1 { get; set; }
        public int id_joueur2 { get; set; }
        public int id_partie { get; set; }
        public Nullable<int> JhP_flag { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Joueur Joueur1 { get; set; }
        public virtual Joueur Joueur2 { get; set; }
        public virtual Partie Partie { get; set; }
    }
}
