//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        public Joueur()
        {
            this.Joueur_has_Partie = new HashSet<Joueur_has_Partie>();
            this.Joueur_has_Partie1 = new HashSet<Joueur_has_Partie>();
            this.Joueur_has_Partie2 = new HashSet<Joueur_has_Partie>();
            this.Partie = new HashSet<Partie>();
            this.Partie1 = new HashSet<Partie>();
            this.Unite = new HashSet<Unite>();
        }
    
        public int id_joueur { get; set; }
        public string pseudo_joueur { get; set; }
        public Nullable<int> nbrpartiesjoues_joueur { get; set; }
        public Nullable<int> nbrpartiesgagnes_joueur { get; set; }
        public Nullable<int> nbrpartiesperdues_joueur { get; set; }
        public Nullable<int> joueur_toUtilisateur { get; set; }
    
        public virtual ICollection<Joueur_has_Partie> Joueur_has_Partie { get; set; }
        public virtual ICollection<Joueur_has_Partie> Joueur_has_Partie1 { get; set; }
        public virtual ICollection<Joueur_has_Partie> Joueur_has_Partie2 { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<Partie> Partie { get; set; }
        public virtual ICollection<Partie> Partie1 { get; set; }
        public virtual ICollection<Unite> Unite { get; set; }
    }
}
