//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thomasEntities3 : DbContext
    {
        public thomasEntities3()
            : base("name=thomasEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<Joueur_has_Partie> Joueur_has_Partie { get; set; }
        public virtual DbSet<New_Monde> New_Monde { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
