//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thomasEntities : DbContext
    {
        public thomasEntities()
            : base("name=thomasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<Joueur_has_Partie> Joueur_has_Partie { get; set; }
        public virtual DbSet<Monde> Monde { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<Territoire> Territoire { get; set; }
        public virtual DbSet<Type_zone> Type_zone { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
    }
}
