//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monde
    {
        public Monde()
        {
            this.Zone = new HashSet<Zone>();
        }
    
        public int id_monde { get; set; }
        public Nullable<int> monde_topartie { get; set; }
    
        public virtual Partie Partie { get; set; }
        public virtual ICollection<Zone> Zone { get; set; }
    }
}
