//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monde
    {
        public Monde()
        {
            this.Zone = new HashSet<Zone>();
        }
    
        public int id_monde { get; set; }
        public Nullable<int> monde_topartie { get; set; }
    
        public virtual Partie Partie { get; set; }
        public virtual ICollection<Zone> Zone { get; set; }
    }
}
