//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Monde
    {
        public New_Monde()
        {
            this.Zone = new HashSet<Zone>();
        }
    
        public int id_new_monde { get; set; }
        public string nom_new_monde { get; set; }
    
        public virtual ICollection<Zone> Zone { get; set; }
    }
}
