//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partie
    {
        public Partie()
        {
            this.Joueur_has_Partie = new HashSet<Joueur_has_Partie>();
        }
    
        public int id_partie { get; set; }
        public string nom_partie { get; set; }
        public Nullable<int> phase_partie { get; set; }
        public Nullable<int> partie_toJ1 { get; set; }
        public Nullable<int> partie_toJ2 { get; set; }
        public string etat_partie { get; set; }
        public int partie_tonew_monde { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Joueur Joueur1 { get; set; }
        public virtual ICollection<Joueur_has_Partie> Joueur_has_Partie { get; set; }
        public virtual New_Monde New_Monde { get; set; }
    }
}
