//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partie
    {
        public Partie()
        {
            this.Joueur_has_Partie = new HashSet<Joueur_has_Partie>();
            this.Monde = new HashSet<Monde>();
        }
    
        public int id_partie { get; set; }
        public string nom_partie { get; set; }
        public Nullable<int> phase_partie { get; set; }
        public Nullable<int> partie_toJ1 { get; set; }
        public Nullable<int> partie_toJ2 { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Joueur Joueur1 { get; set; }
        public virtual ICollection<Joueur_has_Partie> Joueur_has_Partie { get; set; }
        public virtual ICollection<Monde> Monde { get; set; }
    }
}
