//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unite
    {
        public int id_unite { get; set; }
        public string nom_unite { get; set; }
        public Nullable<int> position_unite { get; set; }
        public Nullable<int> joueur_unite { get; set; }
    
        public virtual Joueur Joueur { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
