//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.Unite = new HashSet<Unite>();
            this.Zone1 = new HashSet<Zone>();
            this.Zone2 = new HashSet<Zone>();
        }
    
        public int id_zone { get; set; }
        public string nom_zone { get; set; }
        public Nullable<int> coordonneesX_zone { get; set; }
        public Nullable<int> coordonneesY_zone { get; set; }
        public Nullable<int> zone_toMonde { get; set; }
    
        public virtual Monde Monde { get; set; }
        public virtual ICollection<Unite> Unite { get; set; }
        public virtual ICollection<Zone> Zone1 { get; set; }
        public virtual ICollection<Zone> Zone2 { get; set; }
    }
}
